# ==========================================
# reports.py
# ==========================================

import tkinter as tk
from tkinter import messagebox
import sqlite3
import os

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph


class ReportWindow:

    def __init__(self, root):

        self.window = tk.Toplevel(root)
        self.window.title("Generate Reports")
        self.window.geometry("500x300")
        self.window.configure(bg="white")

        title = tk.Label(
            self.window,
            text="Pet Report Generator",
            font=("Arial",20,"bold"),
            bg="#3F51B5",
            fg="white",
            pady=10
        )

        title.pack(fill="x")

        frame = tk.Frame(self.window,bg="white")
        frame.pack(pady=40)

        tk.Label(
            frame,
            text="Pet ID",
            font=("Arial",12,"bold"),
            bg="white"
        ).grid(row=0,column=0,padx=10,pady=10)

        self.pet_id = tk.Entry(frame,width=20)
        self.pet_id.grid(row=0,column=1)

        tk.Button(

            frame,

            text="Generate TXT",

            bg="green",

            fg="white",

            width=18,

            command=self.generate_txt

        ).grid(row=1,column=0,pady=20)

        tk.Button(

            frame,

            text="Generate PDF",

            bg="blue",

            fg="white",

            width=18,

            command=self.generate_pdf

        ).grid(row=1,column=1,pady=20)

    # =====================================
    # Get Pet Details
    # =====================================

    def get_pet(self):

        conn = sqlite3.connect("petcare.db")
        cursor = conn.cursor()

        cursor.execute(

            "SELECT * FROM pets WHERE pet_id=?",

            (self.pet_id.get(),)

        )

        pet = cursor.fetchone()

        conn.close()

        return pet

    # =====================================
    # TXT Report
    # =====================================

    def generate_txt(self):

        pet = self.get_pet()

        if pet is None:

            messagebox.showerror(
                "Error",
                "Pet Not Found"
            )

            return

        filename = f"Pet_Report_{pet[0]}.txt"

        with open(filename,"w") as file:

            file.write("PET HEALTH REPORT\n")
            file.write("="*40+"\n\n")

            file.write(f"Pet ID : {pet[0]}\n")
            file.write(f"Name : {pet[1]}\n")
            file.write(f"Species : {pet[2]}\n")
            file.write(f"Breed : {pet[3]}\n")
            file.write(f"Age : {pet[4]}\n")
            file.write(f"Gender : {pet[5]}\n")
            file.write(f"Weight : {pet[6]}\n")
            file.write(f"Owner : {pet[7]}\n")
            file.write(f"Contact : {pet[8]}\n\n")

            file.write("Generated by PetCareAI\n")

        messagebox.showinfo(
            "Success",
            f"{filename} Created Successfully."
        )

    # =====================================
    # PDF Report
    # =====================================

    def generate_pdf(self):

        pet = self.get_pet()

        if pet is None:

            messagebox.showerror(
                "Error",
                "Pet Not Found"
            )

            return

        if not os.path.exists("reports"):
            os.makedirs("reports")

        filename = f"reports/Pet_Report_{pet[0]}.pdf"

        doc = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        elements = []

        elements.append(
            Paragraph("<b>PetCareAI Health Report</b>",styles["Title"])
        )

        elements.append(
            Paragraph(f"<b>Pet ID :</b> {pet[0]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Name :</b> {pet[1]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Species :</b> {pet[2]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Breed :</b> {pet[3]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Age :</b> {pet[4]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Gender :</b> {pet[5]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Weight :</b> {pet[6]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Owner :</b> {pet[7]}",styles["BodyText"])
        )

        elements.append(
            Paragraph(f"<b>Contact :</b> {pet[8]}",styles["BodyText"])
        )

        elements.append(
            Paragraph("<br/><b>Generated by PetCareAI</b>",styles["Heading2"])
        )

        doc.build(elements)

        messagebox.showinfo(
            "Success",
            f"PDF Saved as\n{filename}"
        )


# ======================================
# Open Window
# ======================================

def open_report_window(root):

    ReportWindow(root)


# ======================================
# Run Independently
# ======================================

if __name__ == "__main__":

    root = tk.Tk()
    root.withdraw()

    ReportWindow(root)

    root.mainloop()