TUPLE
-> IMMUTABLE
-> ORDERED
-> FIXED DATA
-> ALLOWS DUPLICATES
-> HETEROGENOUS
->

DICT
->KEY VALUE PAIRS
->MUTABLE
->ORDERED
->KEY:UNIQUE,VALUES:NO RESTRICTION(ALLOWS DUPLICATES)
->KEY:IMMUTABLE,VALUES:MUTABLE/IMMUTABLE
operations:membership only( remainimg wont work for this)
