Python 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> from emaillogic import *
... 
... subject = input("Enter email subject: ")
... body = input("Enter email body: ")
... 
... choice = input('''Do you want to send
...                 (1) Single Email or
...                 (2) Bulk Emails? Enter 1 or 2: ''')
... 
... attach_choice = input("Do you want to add attachments? (y/n): ").lower()
... attachments = []
... 
... 
... if attach_choice == "y":
...     files = input("Enter file paths separated by commas: ").split(',')
...     attachments = [f.strip() for f in files]
... 
... if choice == "1":
...     recipient = input("Enter recipient email: ")
...     send_email(recipient, subject, body, attachments)
... 
... elif choice == "2":
...     csv_file = input("Enter path to CSV file with email addresses: ")
...     send_bulk_emails(csv_file, subject, body, attachments)
... else:
...         print("Invalid choice! Please enter 1 or 2.")
... 
... 
... 
... 
... 
... 
... 
... 
...         
... 
... 
